version: '3.8'

services:
  transaction-service:
    image: transaction-app:latest
#    build:
#      context: ./services/transaction_service
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  flight-service:
    image: flight-app:latest
#    build:
#      context: ./services/app
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
